version: "2.0"

services:
  web:
    image: ghcr.io/gabsgj/hackodisha/athenis:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - API_KEY=secret-key-from-akash-env
      - MODEL_NAME=TinyLlama/TinyLlama-1.1B-Chat-v1.0
      - QUANTIZE=8bit
      - REDIS_URL=${REDIS_URL}
      - EXTERNAL_LLM_API_URL=${EXTERNAL_LLM_API_URL}
      - GOFR_URL=http://gofr:8090
      - RATE_LIMIT_PER_MIN=30
      - LOG_LEVEL=info
      - FAST_TEST=0
    resources:
      cpu:
        units: 1
      memory:
        size: 2Gi
      storage:
        size: 5Gi
      gpu:
        units: 1
        attributes:
          vendor:
            nvidia:
              - model: h100
              - model: a100
    
  gofr:
    image: ghcr.io/gabsgj/athenis-gofr:latest
    expose:
      - port: 8090
        to:
          - service: "web"
    env:
      - PORT=8090
      - PY_EXTRACT_SCRIPT=/app/app/utils/extract.py
    resources:
      cpu:
        units: 0.5
      memory:
        size: 512Mi
      storage:
        size: 1Gi

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 5Gi
        gpu:
          units: 1
    gofr:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 10000
        gofr:
          denom: uakt
          amount: 5000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
  gofr:
    dcloud:
      profile: gofr
      count: 1
