version: "2.0"

services:
  web:
    image: ghcr.io/gabsgj/hackodisha/athenis:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - API_KEY=production-key-change-me
      - MODEL_NAME=microsoft/DialoGPT-medium
      - QUANTIZE=8bit
      - RATE_LIMIT_PER_MIN=10
      - LOG_LEVEL=info
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:64
      - CORS_ORIGINS=*
    resources:
      cpu:
        units: 2
      memory:
        size: 8Gi
      storage:
        size: 20Gi
      gpu:
        units: 1
        attributes:
          vendor:
            nvidia:
              - model: rtx4090
              - model: a100
              - model: h100

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          size: 20Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
                - model: a100
                - model: h100
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 50000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
