---
version: "2.0"

services:
  web:
    image: python:3.10
    env:
      - PORT=8080
    command:
      - /bin/sh
      - -c
      - |
        apt-get update && apt-get install -y git
        git clone https://github.com/gabsgj/athenis.git app
        cd app
        pip install -r requirements.txt
        python app/app.py
    expose:
      - port: 8080
        as: 80
        to:
          - global

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 2Gi
  placement:
    westcoast:
      attributes:
        region: us-west
      signedBy:
        anyOf:
          - "akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05"
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    westcoast:
      profile: web
      count: 1
