---
version: "2.0"

services:
  legal-simplifier-ai:
    image: python:3.11-slim
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - API_KEY=hackodisha-akash-ai-2025-secure-key
      # Akash AI Configuration
      - EXTERNAL_LLM_API_URL=https://chatapi.akash.network/api/v1/chat/completions
      - EXTERNAL_LLM_API_KEY=ak_your_actual_akash_ai_key_here
      - EXTERNAL_LLM_API_KEY_HEADER=Authorization
      - EXTERNAL_LLM_API_KEY_SCHEME=Bearer
      - EXTERNAL_LLM_FORMAT=openai
      # App Configuration
      - CORS_ORIGINS=*
      - LOG_LEVEL=info
      - PORT=8080
      - RATE_LIMIT_PER_MIN=20
    command:
      - /bin/sh
      - -c
      - |
        apt-get update && apt-get install -y --no-install-recommends git curl && \
        git clone https://github.com/gabsgj/athenis.git /app && \
        cd /app && \
        pip install --no-cache-dir flask flask-cors werkzeug prometheus-client requests gunicorn python-dotenv pdfminer.six python-docx && \
        gunicorn --bind 0.0.0.0:8080 --workers 2 --worker-class gthread --worker-connections 1000 --timeout 60 app.wsgi:application

profiles:
  compute:
    legal-simplifier-ai:
      resources:
        cpu:
          units: 1000  # 1 CPU core
        memory:
          size: 2Gi    # 2GB RAM
        storage:
          size: 8Gi    # 8GB storage

  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        legal-simplifier-ai:
          denom: uakt
          amount: 15000  # Slightly higher for AI usage

deployment:
  legal-simplifier-ai:
    akash:
      profile: legal-simplifier-ai
      count: 1
