---
version: "2.0"

services:
  athenis:
    image: ghcr.io/gabsgj/hackodisha/athenis:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - API_KEY=ak_prod_2025_secure_cpu_deployment_key_5h2k8w9r
      # Use Akash AI (or any HTTP LLM) instead of OpenAI
      # Example: OpenAI-compatible endpoint (set format=openai), or simple {prompt}->{text}
      - EXTERNAL_LLM_API_URL=https://ai.your-akash-endpoint.example.com/v1/chat/completions
      - EXTERNAL_LLM_API_KEY=your-akash-ai-key
      - EXTERNAL_LLM_API_KEY_HEADER=Authorization
      - EXTERNAL_LLM_API_KEY_SCHEME=Bearer
      - EXTERNAL_LLM_FORMAT=openai
      # Local fallback model (CPU-friendly) if EXTERNAL_LLM_API_URL is unset
      - MODEL_NAME=microsoft/DialoGPT-medium
      - RATE_LIMIT_PER_MIN=20
      - LOG_LEVEL=info
      - CORS_ORIGINS=*

profiles:
  compute:
    athenis:
      resources:
        cpu:
          units: 1000
        memory:
          size: 2Gi
        storage:
          size: 5Gi

  placement:
    akash:
      pricing:
        athenis:
          denom: uakt
          amount: 10000

deployment:
  athenis:
    akash:
      profile: athenis
      count: 1
