---
version: "2.0"

services:
  legal-ai-vllm:
    image: vllm/vllm-openai:latest
    expose:
      - port: 8000
        as: 80
        to:
          - global: true
    command:
      - /bin/bash
      - -c
      - >
        echo "Starting vLLM server with legal-optimized model..." &&
        python -m vllm.entrypoints.openai.api_server 
        --model microsoft/DialoGPT-large
        --host 0.0.0.0 
        --port 8000
        --served-model-name legal-ai
        --max-model-len 4096
        --gpu-memory-utilization 0.8
        --tensor-parallel-size 1
        --dtype float16
        --enable-chunked-prefill
        --max-num-batched-tokens 8192
        --api-key hackodisha-vllm-secure-2025

    env:
      # vLLM Configuration
      - VLLM_WORKER_MULTIPROC_METHOD=spawn
      - VLLM_LOG_LEVEL=INFO
      - CUDA_VISIBLE_DEVICES=0
      
      # Memory Management
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - VLLM_USE_MODELSCOPE=false
      
      # API Settings
      - VLLM_API_KEY=hackodisha-vllm-secure-2025
      - OPENAI_API_KEY=hackodisha-vllm-secure-2025

  athenis-frontend:
    image: python:3.11-slim
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    command:
      - /bin/sh
      - -c
      - >
        export PATH="/usr/bin:/bin:/usr/local/bin:$PATH" &&
        apt-get update &&
        apt-get install -y --no-install-recommends git curl build-essential &&
        /usr/bin/git clone https://github.com/gabsgj/athenis.git /app &&
        cd /app &&
        pip install --no-cache-dir -r requirements-min.txt &&
        pip install --no-cache-dir gunicorn==21.2.0 openai==1.3.0 &&
        gunicorn --bind 0.0.0.0:8080 --workers 2 --worker-class gthread --worker-connections 1000 --timeout 60 app.wsgi:application

    env:
      # External AI Service
      - EXTERNAL_LLM_API_URL=http://legal-ai-vllm:8000/v1
      - EXTERNAL_LLM_API_KEY=hackodisha-vllm-secure-2025
      - EXTERNAL_LLM_MODEL=legal-ai
      
      # Application Settings
      - API_KEY=hackodisha-frontend-secure-2025
      - FAST_TEST=false
      - USE_EXTERNAL_LLM=true
      - CORS_ORIGINS=*
      - LOG_LEVEL=info
      - PORT=8080
      - RATE_LIMIT_PER_MIN=20
      
      # Legal AI Features
      - ENABLE_LEGAL_CONTEXT=true
      - MAX_DOCUMENT_SIZE=10485760
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200

profiles:
  compute:
    legal-ai-vllm:
      resources:
        cpu:
          units: 4
        memory:
          size: 24gb
        storage:
          - size: 100gb
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx4090
                - model: a100
                - model: h100
            ram:
              - size: 16gi
              - size: 24gi
              - size: 40gi
              - size: 80gi
    
    athenis-frontend:
      resources:
        cpu:
          units: 2
        memory:
          size: 4gb
        storage:
          - size: 10gb

  placement:
    akash:
      pricing:
        legal-ai-vllm:
          denom: uakt
          amount: 200000  # Higher for GPU service
        athenis-frontend:
          denom: uakt
          amount: 15000   # Lower for frontend
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash

deployment:
  legal-ai-vllm:
    akash:
      profile: legal-ai-vllm
      count: 1
  athenis-frontend:
    akash:
      profile: athenis-frontend
      count: 1
