name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_REPO_FLASK: your-org/legal-simplifier-flask
  IMAGE_REPO_GOFR: your-org/legal-simplifier-gofr

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v --disable-warnings

  build-docker:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v3

      # Build Flask image
      - name: Build Flask Docker image
        run: |
          echo "Building Flask image..."
          docker build \
            --build-arg API_KEY=${{ secrets.API_KEY }} \
            -t $IMAGE_REPO_FLASK:latest \
            -f Dockerfile .

      # Build GoFR image
      - name: Build GoFR Docker image
        run: |
          echo "Building GoFR image..."
          docker build \
            -t $IMAGE_REPO_GOFR:latest \
            -f gofr/Dockerfile ./gofr

      # Optional: push images to Docker Hub or GHCR
      # - name: Login to Docker
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Flask image
      #   run: docker push $IMAGE_REPO_FLASK:latest
      #
      # - name: Push GoFR image
      #   run: docker push $IMAGE_REPO_GOFR:latest
